spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:80/course
    username: root
    password: 123456

  flyway:
    url: jdbc:postgresql://localhost:80/course
    user: root
    password: 123456
    enabled: true
    locations:
      - 'classpath:db/migration'
